version: '3'

services:
    app:
        build:
          context: .
          dockerfile: ./Dockerfile/Dockerfile
        ports:
            - "8080:8080"
        container_name: golang-test-container
        volumes:
            - "./Gocode:/go"
        tty: true
        depends_on:
            - mysql
        command: go run main.go
    mysql:
        image: mysql:latest
        container_name: mysql-container
        environment:
          MYSQL_ROOT_PASSWORD: root-pass
          MYSQL_DATABASE: golang-test-database
          MYSQL_USER: golang-test-user
          MYSQL_PASSWORD: golang-test-pass
        volumes:
            - "./db/sql:/docker-entrypoint-initdb.d"
